### ISSUE TITLE
Brnocarpark dataset

### ISSUE THREAD

**Issue by gentle1212** [kocurvik/deep_vp#2]
BrnoCarPark dataset not available the scripts given in code requires both datasets brnocarpak and brnocompspeed however brnocarpark dataset is not available. can you please provide the brnocarpark dataset.

**Comment by kocurvik** [comment]
Please contact the corresponding author for the dataset at ibartl@fit.vutbr.cz

Note that you will not need the videos, but only the frames. So your don't have to download everything. Though you do not need the datasets for training or inference on other videos.
