### ISSUE TITLE
testing on a video

### ISSUE THREAD

**Issue by AnilKumar75** [kocurvik/deep_vp#4]
Hello,
I am working on BrnoSpeedDataset, I want to use it for speed estimation but I am unable to see the ground truth on video.
Can you please share the way to implement the dataset on the video to see the results visually? like how to see ground truth speed on video?

I would really appreciate it.
Thanks

**Comment by kocurvik** [comment]
Hello, this code only performs semi-automatic camera calibration. This is only a one step in the whole speed estimation pipeline.

If you want to work with BrnoCompSpeed I recommend checking [this repository](https://github.com/kocurvik/retinanet_traffic_3D) for our paper on vehicle speed estimation. It assumes that cameras are already calibrated using a method from another paper. Check the paper linked in the repo for more info. The code is somewhat messy and it requires TF 1.14 which is difficult to install nowadays, but it should still work and has an "online" option which also visualizes the vehicle tracks. To add speed into the video would require some minor code changes as the official evaluation script for BrnoCompSpeed only requires vehicle positions and camera calibration.
