### ISSUE TITLE
3D bbox construction problem

### ISSUE THREAD

**Issue by robosina** [kocurvik/deep_vp#8]
Dear @kocurvik, I am working on the creation of the 3D bounding boxes, but sometimes the created 3D box does not appear to be in the correct shape, is this normal? (is this method robust to the location of the cars?) 

Please see Car0 in the below image:

![Selection_264](https://user-images.githubusercontent.com/14973524/208086240-f96bbc93-634e-4b40-8eec-b6903dd96bf1.jpg)

I have selected VP1 and VP2 manually or via tracking the cars, and I am extracting the blobs from the cars using instance segmentation(it is accurate) and drawing it on the images just for reference. after that, I'm trying to find tangent lines and the process is the same as the paper.

As far as I can tell, this is not normal since constructing histograms from such bounding boxes will not be appropriate. Would you be able to make any suggestions regarding this matter?

**Comment by kocurvik** [comment]
Hello @robosina,

constructing the 3D bounding box is dependent on the order in which you construct the individual edges and may thus sometimes be unstable. Also the car has to be aligned with the vanishing points for it to make sense and it is possible that car0 in your image is not aligned well enough. Another possibility is that the blob is not accurate and sometimes contains the sideview mirrors and sometimes does not.

Are you using code from this repo or your own? The order in which you construct the edges may need to be changed based on the horizontal position of the vehicle relative to VP1.

**Comment by robosina** [comment]
Dear @kocurvik , I apologize for the late response (There are some medical checks I need to undergo and was unable to respond back).

Yeah, you're right about the alignment, the selected vanishing point is not aligned with the car in that region, please see the image below. (Or perhaps you can see that this is something that we can accurately create the 3D box for that car(`top-left one`))

![image](https://user-images.githubusercontent.com/14973524/208502918-88c7625f-e9d6-4321-ae04-a52bf9d0bfd5.png)

For vanishing point extraction, the [Automatic camera calibration for traffic understanding](http://www.bmva.org/bmvc/2014/files/paper013.pdf) is used. But I've used the below methods:

- deep_vp
- Manual Calib
- the above paper

I may have overlooked something in the steps involved in creating the 3DBoxes, but if you require the code (it is written in C++), I can provide it.

**Comment by kocurvik** [comment]
When I worked with the BrnoCompSpeed dataset I used the included masks for each video and these masks made it so that only vehicles traveling towards the camera were detected. This is also necessary when evaluating the speeds on the dataset.

I would suggest you do the same as the car in the top-left part is an outlier w.r.t to the rest of the vehicles.

**Comment by KOuldamer** [comment]
Thank you for this interesting work,
@robosina could you share the code to draw the 3d bounding boxes please?

**Comment by Sondosmohamed1** [comment]
> Thank you for this interesting work, @robosina could you share the code to draw the 3d bounding boxes please?

i also need to construct the 3d box from vanishing points could you explain the method in gituhb thank you very much

**Comment by robosina** [comment]
> > Thank you for this interesting work, @robosina could you share the code to draw the 3d bounding boxes please?
> 
> i also need to construct the 3d box from vanishing points could you explain the method in gituhb thank you very much

To complete this task, I first read the paper and followed its instructions step by step. There are several steps involved:

- First, you need to identify 'vp1' and 'vp2'. This can be done using various methods, such as using the 'deep_vp' from the repository. You could also use alternative methods involving the accumulated and voting approach.

- Next, you need to segment the cars in the image.

- Lastly, refer back to the paper to understand how the boxes are constructed.

Please note that there are several steps involved, so following the instructions in the paper carefully is important.
